{
    'name': 'ISO 17024 Certification Portal',
    'version': '1.3',
    'summary': 'Portal Pendaftaran Sertifikasi Coating (Benchmark AMPP)',
    'author': 'User Odoo',
    'category': 'Website',
    'depends': ['website', 'auth_signup', 'portal', 'mail', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/email_templates.xml',
        'data/email_template_payment.xml',
        'data/email_template_revision.xml',
        'views/signup_template.xml',
        'views/pending_template.xml',
        'views/application_template.xml',
        'views/step2_template.xml',
        'views/payment_template.xml',
        'views/payment_result_template.xml',
        'views/status_template.xml',
        'views/registration_views.xml',
        'views/backend_views.xml',
        'views/quiz_views.xml',
        'views/quiz_template.xml',
        'views/session_views.xml',
        'views/certification_pages.xml',
        'views/menus.xml',
        # Snippets
        'views/snippets/s_org_structure.xml',
        'views/snippets/s_certification_flow.xml',
        'views/snippets/s_registration_info.xml',
        'views/snippets/s_quality_policy.xml',
        'views/snippets/s_certification_path.xml',
        'views/snippets/s_certification_level.xml',
        'views/snippets/s_our_advantages.xml',
        'views/snippets/s_integrated_security.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'iso17024_portall/static/src/css/snippets.css',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}